run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec

linters-settings:
  gosec:
    excludes:
      - G104 # Suppress unhandled error results
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
